### ISSUE TITLE
$this->Order->createOrder($cartData, $processorClass) Argument type error

### ISSUE THREAD

**Issue by comeonly** [burzum/cakephp-cart-plugin#21]
Hello, I got this error when I'm trying to anonymous checkout.

in [CheckoutController.php#L123-126](https://github.com/burzum/cakephp-cart-plugin/blob/develop/Controller/CheckoutController.php#L123-126)

```php
$processorClass = $this->_mapProcessorClass($processor);
$Processor = $this->_loadPaymentProcessor($processorClass);

$newOrder = $this->Order->createOrder($cartData, $processorClass);
```

I guess `$processorClass` should be string on L124-125 but should be array on L126. What kind of value is expected? How do I fix it?

my config is like this

```php
$config = array(
	'Cart' => array(
		'models' => array(
			'User' => 'Users.User'
		),
		'defaultCurrency' => 'JPY',
		'anonymousCheckout' => true,
		'PaymentMethod' => array(
			'Webpay' => array(
				'name' => 'Dummy Express Checkout',
				'description' => 'Dummy Express Checkout description',
				'class' => 'Webpay',
				'logo' => '',
				'active' => true,
				'processor' => 'WebpayProcessor'
			)
		)
	),
	'WebpayProcessor' => array(
		'sandboxMode' => false,
		'sandbox' => array(
			'apiKey' => '',
			'apiId' => ''
		)
	)
);
```

**Comment by burzum** [comment]
Did you already figure it out? I don't remember, AFAIR it was a string.

**Comment by comeonly** [comment]
I got a int so I thought my config was something wrong as I read source. sorry I gave up to use this and there is no one got same error so I close this issue.
