### ISSUE TITLE
$this->Controller issue on postBuy()?

### ISSUE THREAD

**Issue by brandonjjon** [burzum/cakephp-cart-plugin#24]
Burzum:

I feel confident this is a possible bug as I have looked high and low. Every time I use the postBuy method, the foreign_key is ALWAYS set to 57 which I thought was very random. Upon closer inspection of this code: https://github.com/burzum/cakephp-cart-plugin/blob/develop/Controller/Component/CartManagerComponent.php#L405-L410 - When I pr($this->Controller);die; it always prints out CakeError instead of the controller it's supposed to be. (In my case, TracksController). Do you know what would cause this behavior?

Thanks

**Comment by burzum** [comment]
I think we resolved this long time ago on IRC :)
