### ISSUE TITLE
Documentation Plugin

### ISSUE THREAD

**Issue by marczaq** [burzum/cakephp-cart-plugin#26]
Can You upload documentation how to use plugin? With tutorial how to display product, how to buy product etc.

Now in documentation are nothing.
I do not know what fields in a database I have even

**Comment by burzum** [comment]
I'm not maintaining this plugin any more for free. You've already got a complete and pretty advanced cart implementation for free.

You can hire me to implement it or hire me to write the documentation or buy the CakePHP3 version of it once it is released. I'm not providing personal support for free. Alternatively implement your own cart or move on to another plugin.
